news_sites:
  eluniversal:
    url: https://www.eluniversal.com.mx/
    queries:
      homepage_article_links: '.field-content a'
      article_body: '.field-name-body'
      article_title: '.pane-content h1'
  elpais:
    url: https://www.elpais.com
    queries:
      homepage_article_links: '.articulo-titulo a'
      article_body: ''
      article_title: ''
  glassdoor:
    url: https://www.glassdoor.com/index.htm
  
  linkedin:
    url: https://www.linkedin.com/jobs/search/?keywords=developer
    post_class: ".job-card-search__link-wrapper .js-focusable .disabled .ember-view"
